
/*CHAR INDEX - RETORNA UM INTEIRO
	1º PARÂMETRO -> O QUE EU PROCURO?
	2º PARÂMETRO -> ONDE EU PROCURO?
	3º PARÂMETRO -> A PARTIR DE QUE OCORRÊNCIA? não obrigatório, a PROCURA A PARTIR DA 1ª POSIÇÃO
*/

--PROCURANDO A PARTIR DA POSIÇÃO 1 (DEFAULT)
SELECT
	NOMEALUNO, CHARINDEX('a', NOMEALUNO)	
FROM
	ALUNO
GO

--PROCURANDO A PARTIR DA POSIÇÃO 3 
SELECT
	NOMEALUNO, CHARINDEX('a', NOMEALUNO,3)	
FROM
	ALUNO
GO