CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY IDENTITY,
	NOMEALUNO VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO

/*CONSTRAINTS*/
-- EFETUA CHECAGEM PARA VERIFICAR SE EST� SENDO INSERIDO APENAS M OU F
ALTER TABLE ALUNO 
ADD CONSTRAINT CK_SEXO CHECK (SEXO IN ('M','F'))
GO

/*1 x 1*/
CREATE TABLE ENDERECO(
	IDENDERECO INT NOT NULL PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL CHECK (UF IN ('RJ','SP','MG')),
	ID_ALUNO INT UNIQUE 
)
GO

/* CRIANDO A FK*/
ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (IDALUNO)
GO

/*COMANDOS DE DESCRI플O
	PROCEDURES J� CRIADAS E ARMAZENADAS NO SISTEMA
*/

SP_COLUMNS ALUNO -- MOSTRA DESCRI플O COMPLETA DA TABELA
GO

SP_HELP ALUNO -- MOSTRA COM AINDA MAIS DETALHES A TABELA
GO


