CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT,
	CHECK (TIPO IN('RES','COM','CEL'))
)
GO

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_ALUNO
FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (IDALUNO)
GO

INSERT INTO TELEFONE VALUES ('CEL', '7899987999',6)
INSERT INTO TELEFONE VALUES ('RES', '1234564789',7)
INSERT INTO TELEFONE VALUES ('COM', '1324587951',8)
INSERT INTO TELEFONE VALUES ('CEL', '0045678940',9)
GO

/*PEGA DATA ATUAL*/
SELECT GETDATE()
GO

/*CLAUSULA AMBÍGUA*/

SELECT 
	A.NOMEALUNO, 
	ISNULL(T.TIPO,'N/D') AS TIPO, 
	ISNULL(T.NUMERO,'N/D') AS NUMERO, 
	E.BAIRRO, 
	E.UF
FROM
	ALUNO A LEFT JOIN TELEFONE T ON(A.IDALUNO = T.ID_ALUNO)
	INNER JOIN ENDERECO E ON (A.IDALUNO = E.ID_ALUNO)
GO


