/*
	PROCEDURE DE CADASTRO
*/

CREATE PROCEDURE CADASTRO @NOMEALUNO VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE, @EMAIL VARCHAR(50), @TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
	DECLARE @FK INT
	INSERT INTO ALUNO VALUES (@NOMEALUNO, @SEXO, @NASCIMENTO, @EMAIL)
	
	SET @FK = (SELECT IDALUNO FROM ALUNO WHERE IDALUNO = @@IDENTITY) --@@IDENTITY, GUARDA O ULTIMO IDENTITY INSERIDO NA FUNÇÃO
	
	INSERT INTO TELEFONE values(@TIPO, @NUMERO, @FK)

GO

EXEC CADASTRO 'ELIANE','F','25/04/1985','ELIANE@ELIANE.COM', 'COM','32470371'
GO


