CREATE TABLE SALARIO_RANGE(
	MINSAL MONEY,
	MAXSAL MONEY
)
GO

INSERT INTO SALARIO_RANGE VALUES(3000.00, 6000)
GO


CREATE TRIGGER TG_RANGE
ON DBO.EMPREGADO
FOR INSERT, UPDATE
AS
	DECLARE 
		@MINSAL MONEY,
		@MAXSAL MONEY,
		@ATUALSAL MONEY

	SELECT @MINSAL = MINSAL, @MAXSAL = MAXSAL FROM SALARIO_RANGE

	SELECT @ATUALSAL = I.SALARIO
	FROM inserted I

	IF (@ATUALSAL < @MINSAL)
	BEGIN
		RAISERROR('SALÁRIO MENOR QUE O PISO', 16,1)
		ROLLBACK TRANSACTION
	END

	IF (@ATUALSAL > @MAXSAL)
	BEGIN
		RAISERROR('SALÁRIO MAIOR QUE O TETO', 16,1)
		ROLLBACK TRANSACTION
	END	
GO

SELECT  * FROM EMPREGADO

update EMPREGADO
set SALARIO = 1000
where IDEMPREGADO = 1
GO

SP_HELPTEXT TG_RANGE -- IMPRIME O CÓDIGO DA TRIGGER
GO