
CREATE TABLE CARROS(
	CARRO VARCHAR(20),
	FABRICANTE VARCHAR(30)
)
GO

SELECT * FROM CARROS

INSERT INTO CARROS VALUES('KA','FORD')
INSERT INTO CARROS VALUES('FIESTA','FORD')
INSERT INTO CARROS VALUES('FOCUS','FORD')
INSERT INTO CARROS VALUES('CLIO','RENAULT')
INSERT INTO CARROS VALUES('SANDERO','RENAULT')
INSERT INTO CARROS VALUES('CHEVETTE','CHEVROLET')
INSERT INTO CARROS VALUES('ONIX','CHEVROLET')
INSERT INTO CARROS VALUES('PALIO','FIAT')
INSERT INTO CARROS VALUES('TORO','FIAT')
INSERT INTO CARROS VALUES('UNO','FIAT')
INSERT INTO CARROS VALUES('MAREA','FIAT')
GO

/*BLOCO DE DECLARAÇÃO DE VARIÁVEUS*/
DECLARE
	@V_CONT_FORD INT,
	@V_CONT_FIAT INT
BEGIN
	--METODO_1 - SELECT PARA RETORNAR UMA SIMPLES COLUNA E UM SÓ RESULTADO
	SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS WHERE FABRICANTE = 'FORD')
	PRINT 'QTD FORD : ' + CAST(@V_CONT_FORD AS VARCHAR)

	--METODO 2

	SELECT @V_CONT_FIAT = COUNT(*) FROM CARROS WHERE FABRICANTE = 'FIAT'
	PRINT 'QTD FIAT : ' + CAST(@V_CONT_FIAT AS VARCHAR)
END
GO